### ISSUE TITLE
Uploading bin to David Welch bootloader isn't working

### ISSUE THREAD

**Issue by manuel-rabade** [steve-bate/ChibiOS-RPi#1]
Hello,

If I copy my ch.bin to kernel.img in my SD card everything works fine, but if I upload it to the bootloader05 or bootloader04 from David Welch nothing happens. The bootloaders are working fine because if I upload David Welch blinker example they works. Any suggestions?

Thank you!

**Comment by manuel-rabade** [comment]
The bootloader works fine with minicom in Linux or Mac OS (vía MacPorts), I think it has some kind of incompatibilty with zterm for Mac OS.

Thank you!

**Comment by zerotri** [comment]
I realize this has been closed for quite some time now but I think it is worth mentioning that in ZTerm you have to set the Transfer Convert setting to Binary rather than the default option otherwise it will not work properly. Tested with recent versions of David Welch's bootloader05.
